[APPSEC-793] Specify misc top 50 secrets
SonarSource/sonar-text pull request #141
Opened 2023-06-21 12:54 UTC by gaetan-ferry-sonarsource

2023-06-27 13:01 UTC, jamie-anderson-sonarsource requested changes

2023-06-28 08:08 UTC, gaetan-ferry-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/django.yaml
> +              - "*/settings.py"
Agreed. Considering the unspecific type of secret here, I'd rather not try to cover a lot of corner cases.

2023-06-28 08:08 UTC, gaetan-ferry-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/spotify.yaml
> +        name: OpenWeather API keys should not be disclosed
oopsy

2023-06-28 09:44 UTC, jamie-anderson-sonarsource requested changes

2023-06-28 09:44 UTC, jamie-anderson-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/django.yaml
> +          patternNot: "(?i)({{.*?}}|sample|example|x{4,}|0{4,})"
The opening curly braces near the start of the pattern need to be escaped. It appears that the closing braces are ok, at least according to Regex101.

```suggestion
          patternNot: "(?i)(\\{\\{.*?}}|sample|example|x{4,}|0{4,})"
```

2023-06-28 09:44 UTC, jamie-anderson-sonarsource approved these changes
LGTM

2023-06-29 06:44 UTC, merged