[APPSEC-790] Detect top secrets related to Messaging systems.
SonarSource/sonar-text pull request #142
Opened 2023-06-26 12:07 UTC by gaetan-ferry-sonarsource

2023-06-27 12:06 UTC, jamie-anderson-sonarsource requested changes

2023-06-28 08:01 UTC, gaetan-ferry-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/sendgrid.yaml
> +          pattern: "\\b(SG\\.[a-zA-Z0-9]{20,}\\.[a-zA-Z0-9_\\-]{40,})\\b"
Makes sense. I assume you mean `_` instead of `\\`.

2023-06-28 08:04 UTC, jamie-anderson-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/sendgrid.yaml
> +          pattern: "\\b(SG\\.[a-zA-Z0-9]{20,}\\.[a-zA-Z0-9_\\-]{40,})\\b"
Yes 🤦‍♂️

2023-06-28 08:06 UTC, jamie-anderson-sonarsource requested changes

2023-06-28 08:06 UTC, jamie-anderson-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/sendgrid.yaml
> +            patternAround: ""
Somehow you missed this one.

```suggestion
```

2023-06-28 08:07 UTC, jamie-anderson-sonarsource approved these changes
I fixed the useless patternAround and now it LGTM

2023-06-28 08:19 UTC, merged