S6698: Improved postgresql secret detection precision
SonarSource/sonar-text pull request #207
Opened 2023-08-25 06:44 UTC by daniel-teuchert-sonarsource

2023-08-25 14:16 UTC, loris-s-sonarsource requested changes
Please switch the comments to what I suggested. It's gonna look great 👍 (I hope)

Then, please add this case, reported by a user:

``` cpp
swprintf(connectionString, 1024, L"DRIVER=%ls;ServerName=%ls;Port=%ls;UID=%ls;Database=%ls;PWD=%ls;SSLMode=%ls",...);
```

For the environment let's try to be a little narrower, for example by checking only for 

- process.env.VAR for JS
- os.getenv for python
- etc. (see the excel file)

2023-08-25 14:16 UTC, loris-s-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/postgresql.yaml
> +          # e.g. os.getenv('Password'), os.environ["password"], env("Password")
I suggest removing all these lines to provide examples, as well as the why of patternNot. Such as :

``` yaml
          # Potential FPs here are environment variables, templates and string substitutions, such as
          # - $my_password
          # - [My Password]
          # - <My Password>
          # - %s
          # - {{MyPassword}}
          # - $(mypassword)
          # - ${mypassword}
          # - getenv("PASS")
```

To do so, just use chatgpt with this prompt:

```
generate a string that would satisfy a given regex without telling anything else. say YES if you understand the assignment.
```

and then send the big regex with markdown backticks, it explains everything

Then, ensure that everything is actually right and add them as comments. I think this way it's gonna be very clear and great for maintainability 👍

2023-08-28 07:23 UTC, daniel-teuchert-sonarsource commented
> For the environment let's try to be a little narrower, for example by checking only for
> 
> * process.env.VAR for JS
> * os.getenv for python
> * etc. (see the excel file)

I tried to narrow it down with the "\b". What kind of false negative do you think could happen with this?

2023-08-29 08:48 UTC, loris-s-sonarsource approved these changes
LGTM. I tried experimenting and creating a provider post block but it looks like it is not really possible

2023-08-29 09:49 UTC, loris-s-sonarsource requested changes
technically LGTM but maintainability requests

2023-08-29 09:49 UTC, loris-s-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/postgresql.yaml
> +            \\b(get)?env(iron)?\\b"
I suggest removing as much patternNot as possible to try to clean up as much as we can, and adding that to the provider detection block instead:

```
  detection:
    post:
      # Potential FPs here are environment variables, templates and string substitutions, such as
      # - $my_password
      # - $db_password
      # - [mypass123]
      # - <example-password>
      # - %s
      # - {{MyPassword}}
      # - $(mypassword)
      # - ${mypassword}
      # - os.getenv("PASS")
      # - os.environ['PASS']
      # - `myPassword`
      # - *********
      # - None
      patternNot:
        "(?i)\
        ^(\\$[a-z_]*)?(db|my)?_?pass(word|wd)?|\
        ^\\[[\\w\\t \\-]+\\]$|\
        <[\\w\\t \\-]+>?|\
        ^%s$|\
        ^\\{+[^}]*\\}+$|\
        ^\\$\\(\\w+\\)$|\
        \\$\\{\\w+(:-\\w+)?\\}|\
        ^\\$[{(]|\
        \\b(get)?env(iron)?\\b|\
        ^`[a-z]+|\
        ^\\*{3,}$|\
        ^None$"
```

2023-08-29 09:49 UTC, loris-s-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/postgresql.yaml
> +          containsSecret: false
I suggest removing the "ENV" since it's python and not Dockerfiles

2023-08-29 09:49 UTC, loris-s-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/postgresql.yaml
> +          containsSecret: false
same about dockerfile and python

2023-08-29 09:49 UTC, loris-s-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/postgresql.yaml
> +          patternNot: "^(db|my)?_?pass(word|wd)?$|\
```suggestion
          patternNot:
            "^(db|my)?_?pass(word|wd)?$|\            
```

2023-08-29 09:49 UTC, loris-s-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/postgresql.yaml
>            pattern: "\\bPG_PASSWORD=(?!\\\\?[\"'])([^\\s]+)(?:$|\\s)"
```suggestion
          # looks for occurrences of the string `PG_PASSWORD=` followed by a value that is not enclosed in single or double quotes.
          pattern: "\\bPG_PASSWORD=(?!\\\\?[\"'])([^\\s]+)(?:$|\\s)"
```

2023-09-01 14:42 UTC, loris-s-sonarsource approved these changes
LGTM !

2023-09-04 14:53 UTC, merged