Modify S6684: Improve subscription key detections
SonarSource/sonar-text pull request #240
Opened 2023-09-12 15:58 UTC by loris-s-sonarsource

2023-09-12 15:58 UTC, loris-s-sonarsource commented on sonar-text-plugin/src/main/resources/org/sonar/plugins/secrets/configuration/azure.yaml
> +
```suggestion
          # These are well-known keys used in emulators only
```

2023-09-14 07:42 UTC, daniel-teuchert-sonarsource requested changes
Nice solution!
Just one thing:
Maybe while you are at it add the examples from RSPEC as test cases?

2023-09-14 08:55 UTC, loris-s-sonarsource commented
@daniel-teuchert-sonarsource Done, I also made a new PR in rspec:  https://github.com/SonarSource/rspec/pull/3072

2023-09-14 09:46 UTC, daniel-teuchert-sonarsource approved these changes
LGTM!

2023-09-14 09:49 UTC, merged